server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhst:3306/sql50?serverTimezone = Asia/Shanghai & useUnicode=true& characterEncoding = utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

